version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.compose
    volumes:
      # - ./src:/src
      # - ./assets:/assets
      - ./:/app
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*