version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile.compose
    volumes:
      - ./src:/src
      - ./assets:/assets
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*